### PR TITLE
fix-small-problems

### LINKED ISSUE #19: Take Assignment page
The page for students to take the assignment/test. Students should have the ability to select answers and submit the assignment.

possible additions would be a time limit.

### LINKED ISSUE #86: Students and teachers should only see buttons that they can use
Delete and Edit button shows up in quizzes and courses no matter if they are allowed to perform the action.

### LINKED ISSUE #87: Students should not be allowed to change quizzes
Currently they can edit and delete them because cancancan is disabled in the controller.

### LINKED ISSUE #88: Students should only see courses and quizzes they are "linked/assigned" to

### LINKED ISSUE #90: Questions should have a correct answer

### PR DESCRIPTION
**Pull request by egemix**
Closes #19 
Closes #86 
Closes #87 
Closes #88 
Closes #90

### CODE REVIEW

File: src/app/models/question.rb [hunk 1]
```diff
@@ -1,5 +1,5 @@
 class Question < ApplicationRecord
-	belongs_to :quiz
-	has_many :answers, :dependent => :destroy
-	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
+	has_many :answers
+	belongs_to :quizzes
+	accepts_nested_attributes_for :answers, allow_destroy: true
```
Comment (kmaus) [inline src/app/models/question.rb]: Why were these changes made? The lambda prevented blank answers from existing, and the `dependent => destroy` said that if the question is deleted, delete its answers as well.

File: src/app/models/quiz.rb [hunk 2]
```diff
@@ -1,6 +1,7 @@
 class Quiz < ApplicationRecord
   validates :title, presence: true
+  has_many :questions
```
Comment (kmaus) [inline src/app/models/quiz.rb]: Why were these changes made? The lambda prevented blank questions from existing, and the `dependent => destroy` said that if the quiz is deleted, delete its questions as well.

File: src/db/migrate/20170322061738_add_quiz_to_question.rb [hunk 3]
```diff
@@ -1,5 +0,0 @@
-class AddQuizToQuestion < ActiveRecord::Migration[5.0]
-  def change
-    add_reference :questions, :quiz, foreign_key: true
-  end
-end
```
Comment (kmaus) [inline src/db/migrate/20170322061738_add_quiz_to_question.rb]: @mikevo am I right to think that deleting migration files is bad for the db?

**Comment by mikevo** [comment]
deleting a migration file is bad for newly setting up the db, and whenever someone has already done this migration.

so yes, never ever delete a migration file. making a new one and changing the current db setup (all previous migrations are applied) is the way to go.

File: src/app/controllers/courses_controller.rb [hunk 4]
```diff
@@ -1,6 +1,6 @@
 class CoursesController < ApplicationController
   before_action :set_course, only: [:show, :edit, :update, :destroy]
-  load_and_authorize_resource
+  authorize_resource :class => false
```
Comment (mikevo) [inline src/app/controllers/courses_controller.rb]: Why do you need to change this?

File: src/app/controllers/courses_controller.rb [hunk 5]
```diff
@@ -53,13 +52,13 @@ def destroy
...
 
   private
-    # Use callbacks to share common setup or constraints between actions.
-    def set_course
-      @course = Course.find(params[:id])
-    end
+  # Use callbacks to share common setup or constraints between actions.
+  def set_course
+    @course = Course.find(params[:id])
+  end
```
Comment (mikevo) [inline src/app/controllers/courses_controller.rb]: please modify your IDE to use the correct indent type (.editorconfig contains the config) such changes should not happen

File: src/app/controllers/add_quiz_id_to_questions_controller.rb [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+    # Use callbacks to share common setup or constraints between actions.
+    def set_add_quiz_id_to_question
+      @add_quiz_id_to_question = AddQuizIdToQuestion.find(params[:id])
+    end
+
+    # Never trust parameters from the scary internet, only allow the white list through.
+    def add_quiz_id_to_question_params
+      params.fetch(:add_quiz_id_to_question, {})
+    end
+end
```
Comment (mikevo) [inline src/app/controllers/add_quiz_id_to_questions_controller.rb]: What does this controller? The name sounds like a migration file which does not need a controller. If this is the case remove it including all other stuff that is not needed

File: src/app/controllers/quizzes_controller.rb [hunk 7]
```diff
@@ -30,27 +27,60 @@ def create
...
-        redirect_to @quiz
-      else
-        render 'edit'
-      end
+    if @quiz.update(quiz_params)
+      redirect_to @quiz
+    else
+      render 'edit'
+    end
+
```
Comment (mikevo) [inline src/app/controllers/quizzes_controller.rb:45]: i guess this is the wrong indent again

File: src/app/controllers/quizzes_controller.rb [hunk 8]
```diff
@@ -30,27 +27,60 @@ def create
...
 
+    Result.create(student_id: current_user.id, quiz_id: params[:id], marks: @marks)
+
+  end
+
+  private
+  def quiz_params
+    params.require(:quiz).permit(:title,:course_id, questions_attributes: [:id, :question, :done , :_destroy, answers_attributes: [:id, :option,:is_correct, :_destroy]])
+  end
+
```
Comment (mikevo) [inline src/app/controllers/quizzes_controller.rb]: Are you sure that this way of doing it will work out in the end because it differs from the purposed way that we talked about in some of the team meetings on Wednesdays.

File: src/app/controllers/users_controller.rb [hunk 9]
```diff
@@ -53,6 +53,6 @@ def change_role
   private
 
   def user_params
-    params.require(:user).permit(:email, :password, :password_confirmation, :username)
+    params.require(:user).permit(:email, :password, :password_confirmation, :username, :role)
```
Comment (mikevo) [inline src/app/controllers/users_controller.rb]: Why is this change necessary? I think we do not want to accept the role form the UI in general.

File: src/app/models/course.rb [hunk 10]
```diff
@@ -2,5 +2,4 @@ class Course < ApplicationRecord
   belongs_to :teacher, class_name: "User"
   has_and_belongs_to_many :students, join_table: :courses_students, class_name: "User"
   accepts_nested_attributes_for :students
-	has_many :quizzes, :dependent => :destroy
```
Comment (mikevo) [inline src/app/models/course.rb]: Why should we keep the quizzes if the course gets destroyed?

File: src/app/models/question.rb (hunk 1 above)
Comment (mikevo) [reply src/app/models/question.rb]: I agree with @kmaus this was fine before. In future please ask before doing such changes.

File: src/app/views/courses/_form.html.erb [hunk 11]
```diff
@@ -1,32 +1,32 @@
...
-  <%= f.submit "Create", class: "btn btn-primary" %>
-  <% else %>
-  <%= f.submit "Update", class: "btn btn-primary" %>
-  <% end %>
+    <% if @course.id.nil? %>
+        <%= f.submit "Create", class: "btn btn-primary" %>
+    <% else %>
+        <%= f.submit "Update", class: "btn btn-primary" %>
+    <% end %>
 <% end %>
```
Comment (mikevo) [inline src/app/views/courses/_form.html.erb]: Editor indent!

File: src/app/views/courses/index.html.erb [hunk 12]
```diff
@@ -1,26 +1,26 @@
...
+            <div class="quiz-card-contents">
+              <h2><%= course.name %></h2>
+              <p><%= link_to "View Course", {:action => 'show', :id => course.id} %></p>
+            </div>
           </div>
         </div>
-      </div>
     <% end %>
   </div>
 </div>
```
Comment (mikevo) [inline src/app/views/courses/index.html.erb]: Editor indent

File: src/db/migrate/20170322061637_create_questions.rb [hunk 13]
```diff
@@ -1,9 +1,10 @@
 class CreateQuestions < ActiveRecord::Migration[5.0]
   def change
     create_table :questions do |t|
-      t.text :content
+      t.string :question
```
Comment (mikevo) [inline src/db/migrate/20170322061637_create_questions.rb]: This is the reason why some tests and the build are failing.

Never ever change a migration file that is in the master!

File: src/db/migrate/20170322061637_create_questions.rb [hunk 14]
```diff
@@ -1,9 +1,10 @@
...
 
       t.timestamps
     end
+    add_reference :questions, :quizzes, index: true
```
Comment (mikevo) [inline src/db/migrate/20170322061637_create_questions.rb]: Change here in the wrong place! make a new migration file if necessary

File: src/db/migrate/20170322061700_create_answers.rb [hunk 15]
```diff
@@ -1,9 +1,11 @@
 class CreateAnswers < ActiveRecord::Migration[5.0]
   def change
     create_table :answers do |t|
-      t.string :content
+      t.string :option
+      t.string :is_correct
 
       t.timestamps
     end
+    add_reference :answers, :questions, index: true
```
Comment (mikevo) [inline src/db/migrate/20170322061700_create_answers.rb]: Changes are not allowed here. Make a new migration file.

File: src/db/migrate/20170322061905_add_question_to_answer.rb [hunk 16]
```diff
@@ -1,5 +0,0 @@
-class AddQuestionToAnswer < ActiveRecord::Migration[5.0]
-  def change
-    add_reference :answers, :question, foreign_key: true
-  end
-end
```
Comment (mikevo) [inline src/db/migrate/20170322061905_add_question_to_answer.rb]: Not allowed! New migration file.

File: src/db/migrate/20170422014256_add_question_id_to_answers.rb [hunk 17]
```diff
@@ -0,0 +1,5 @@
+class AddQuestionIdToAnswers < ActiveRecord::Migration[5.0]
+  def change
+    add_column :answers, :question_id, :integer
+  end
+end
```
Comment (mikevo) [inline src/db/migrate/20170422014256_add_question_id_to_answers.rb]: Questions and answers are already linked in the db so why linking them again?

File: src/db/migrate/20170422014344_add_quiz_id_to_question.rb [hunk 18]
```diff
@@ -0,0 +1,5 @@
+class AddQuizIdToQuestion < ActiveRecord::Migration[5.0]
+  def change
+    add_column :questions, :quiz_id, :integer
+  end
+end
```
Comment (mikevo) [inline src/db/migrate/20170422014344_add_quiz_id_to_question.rb]: Quizzes and questions are already linked in the db so why do you want to link them again?

File: src/db/seeds.rb [hunk 19]
```diff
@@ -6,4 +6,8 @@
 #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
 #   Character.create(name: 'Luke', movie: movies.first)
 # TODO: change email address
-User.create(username: 'admin', email: 'admin@example.com', password: 'admin', password_confirmation: 'admin', role: 'admin')
+User.create(username: 'admin', email: 'admin@example.com', password: 'admin', password_confirmation: 'admin',role: 'admin')
+teacher = User.create(username: 'teacher', email: 'teacher@example.com', password: 'teacher', password_confirmation: 'teacher', role: 'teacher')
+
+course = Course.create! name: "Computer Course", teacher_id: teacher.id
+Quiz.create! title: "Computer Science ", course_id: course.id
```
Comment (mikevo) [inline src/db/seeds.rb]: Why should we add  these things to a production environment? The admin user is intended to bootstrap the whole sys like a root user in unix.

The rest should go into test/fixtures if you need them for your (unit) tests.

File: src/test/controllers/add_quiz_id_to_questions_controller_test.rb [hunk 20]
```diff
@@ -0,0 +1,48 @@
...
+  end
+
+  test "should destroy add_quiz_id_to_question" do
+    assert_difference('AddQuizIdToQuestion.count', -1) do
+      delete add_quiz_id_to_question_url(@add_quiz_id_to_question)
+    end
+
+    assert_redirected_to add_quiz_id_to_questions_url
+  end
+end
```
Comment (mikevo) [inline src/test/controllers/add_quiz_id_to_questions_controller_test.rb]: Is there a reason for adding this test and its controller?
I guess this was generated with the migration and should be removed.

File: src/test/models/result_test.rb [hunk 21]
```diff
@@ -0,0 +1,7 @@
+require 'test_helper'
+
+class ResultTest < ActiveSupport::TestCase
+  # test "the truth" do
+  #   assert true
```
Comment (mikevo) [inline src/test/models/result_test.rb]: There should be something in here

File: src/test/models/add_quiz_id_to_question_test.rb [hunk 22]
```diff
@@ -0,0 +1,7 @@
+require 'test_helper'
+
+class AddQuizIdToQuestionTest < ActiveSupport::TestCase
+  # test "the truth" do
+  #   assert true
```
Comment (mikevo) [inline src/test/models/add_quiz_id_to_question_test.rb]: This does not test anything -> useless

**Review by mikevo — CHANGES_REQUESTED** [review]
I think this PR needs a little love before it is ready to go into master.

File: src/app/models/quiz.rb [hunk 23]
```diff
@@ -1,6 +1,7 @@
...
+	has_many :answers
+  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
   belongs_to :course
-  has_many :questions, :dependent => :destroy
-  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
```
Comment (mikevo) [inline src/app/models/quiz.rb]: I think wee need those two lines

**Review by mikevo — APPROVED** [review]
